name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '.github/**'
      - '**.md'
      - '**.yml'
  release:
    types: [published]

permissions:
  contents: read
  packages: write
    
env:
  REGISTRY: "ghcr.io"
  GHCR_ORG: "The-Water-Museum"
  CONTAINER_NAME: "neobuild-base"
  CONTAINER_TAG: "latest"

jobs:
  publish-container:
    name: Publish Container to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${GHCR_ORG,,}" >>${GITHUB_ENV}
      - name: Set container tag
        run: |
          if [[ "${{github.ref_name}}" == "main" ]]; then
            echo "CONTAINER_TAG=latest" >>${GITHUB_ENV}
          else
            echo "CONTAINER_TAG=${{github.ref_name}}" >>${GITHUB_ENV}
          fi
      - name: Build and publish image
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}
          docker push ghcr.io/${{ env.REPO }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}